"""Configuration generation module."""

import json
import os
from pathlib import Path
from typing import Optional, Dict, Any

from src.prompt.prompt_builder import PromptBuilder
from src.llm.databricks_llm import DatabricksFoundationModelClient, DatabricksLLMClient
from src.utils.benchmark_extractor import (
    extract_all_benchmarks,
    merge_benchmarks_into_config,
    validate_benchmarks
)
from src.utils.sql_validator import SQLValidator
from src.utils.instruction_scorer import InstructionQualityScorer


def generate_config(
    requirements_path: str,
    output_path: str = "output/genie_space_config.json",
    model: str = "databricks-gpt-5-2",
    endpoint: Optional[str] = None,
    context_doc: str = "src/prompt/templates/curate_effective_genie.md",
    output_doc: str = "src/prompt/templates/genie_api.md",
    max_tokens: int = 16000,
    temperature: float = 0.1,
    no_reasoning: bool = False,
    faq_section: str = "## 📊 질문 목록 (FAQ)",
    databricks_host: Optional[str] = None,
    databricks_token: Optional[str] = None,
    validate_sql: bool = True,
    validate_instructions: bool = True,
    validation_output: Optional[str] = None,
    verbose: bool = True
) -> Dict[str, Any]:
    """
    Generate Genie space configuration with direct benchmark extraction.
    
    This function:
    1. Generates the configuration using LLM (for tables, instructions, examples, etc.)
    2. Extracts benchmarks DIRECTLY from requirements document (bypassing LLM)
    3. Merges the extracted benchmarks into the configuration
    4. Saves the final configuration
    
    Args:
        requirements_path: Path to requirements document
        output_path: Output file path for generated config
        model: Foundation model to use (e.g., databricks-gpt-5-2)
        endpoint: Custom serving endpoint name (alternative to foundation model)
        context_doc: Path to context document (best practices)
        output_doc: Path to output format document (API docs)
        max_tokens: Maximum tokens to generate
        temperature: Sampling temperature (0.0-1.0)
        no_reasoning: Skip reasoning in LLM output
        faq_section: FAQ section title to extract benchmarks from
        databricks_host: Databricks workspace URL
        databricks_token: Databricks personal access token
        validate_sql: Run SQL validation on generated queries
        validate_instructions: Run instruction quality scoring
        validation_output: Optional path to save validation report
        verbose: Print progress messages
        
    Returns:
        dict: Generated configuration
        
    Raises:
        ValueError: If credentials are missing
        Exception: If generation or extraction fails
    """
    # Get credentials
    host = databricks_host or os.getenv("DATABRICKS_HOST")
    token = databricks_token or os.getenv("DATABRICKS_TOKEN")
    
    if not host or not token:
        raise ValueError(
            "DATABRICKS_HOST and DATABRICKS_TOKEN must be set. "
            "Either set environment variables or pass as arguments."
        )
    
    # Ensure output directory exists
    output_path_obj = Path(output_path)
    output_path_obj.parent.mkdir(parents=True, exist_ok=True)
    
    # =========================================================================
    # STEP 1: Generate configuration with LLM
    # =========================================================================
    if verbose:
        print("📝 Generating configuration with LLM...")
    
    # Build prompt
    builder = PromptBuilder(
        context_doc_path=context_doc,
        output_doc_path=output_doc,
        input_data_path=requirements_path
    )
    
    if no_reasoning:
        prompt = builder.build_prompt()
    else:
        prompt = builder.build_prompt_with_reasoning()
    
    if verbose:
        print(f"   Prompt: {len(prompt)} characters")
    
    # Initialize LLM client
    if endpoint:
        if verbose:
            print(f"   Using custom endpoint: {endpoint}")
        llm_client = DatabricksLLMClient(
            endpoint_name=endpoint,
            databricks_host=host,
            databricks_token=token
        )
    else:
        if verbose:
            print(f"   Using foundation model: {model}")
        llm_client = DatabricksFoundationModelClient(
            model_name=model,
            databricks_host=host,
            databricks_token=token
        )
    
    # Generate configuration
    if verbose:
        print(f"   Calling LLM (max_tokens={max_tokens}, temperature={temperature})...")
        print("   This may take 30-60 seconds...")
    
    response = llm_client.generate_genie_config(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature
    )
    
    if verbose:
        print("   ✓ Configuration generated by LLM")
    
    # Extract config
    config_data = response.model_dump()
    
    # Show summary
    if verbose:
        config = config_data["genie_space_config"]
        print(f"\n   Space Name: {config['space_name']}")
        print(f"   Tables: {len(config['tables'])}")
        print(f"   Instructions: {len(config['instructions'])}")
        print(f"   Example SQL Queries: {len(config['example_sql_queries'])}")
        print(f"   LLM-Generated Benchmarks: {len(config.get('benchmark_questions', []))}")
    
    # =========================================================================
    # STEP 2: Extract benchmarks directly from requirements
    # =========================================================================
    if verbose:
        print("\n📊 Extracting benchmarks from requirements...")
    
    benchmarks = extract_all_benchmarks(
        requirements_path=requirements_path,
        include_faq=True,
        include_sample_queries=True,
        faq_section_title=faq_section
    )
    
    # Count by type
    faq_count = sum(1 for bm in benchmarks if bm.get('source') == 'faq')
    sample_query_count = sum(1 for bm in benchmarks if bm.get('source') == 'sample_query')
    
    if verbose:
        print(f"   ✓ Extracted {len(benchmarks)} benchmarks")
        print(f"     - FAQ questions: {faq_count}")
        print(f"     - Sample queries: {sample_query_count}")
    
    # Validate benchmarks
    report = validate_benchmarks(benchmarks)
    if verbose:
        print(f"   Validation: {report['valid_count']}/{report['total_count']} valid")
        if report['issues']:
            print(f"   ⚠ {len(report['issues'])} validation issues")
    
    # =========================================================================
    # STEP 3: Merge benchmarks into configuration
    # =========================================================================
    if verbose:
        print("\n🔗 Merging benchmarks into configuration...")
    
    original_count = len(config_data["genie_space_config"].get("benchmark_questions", []))
    
    config_data = merge_benchmarks_into_config(
        config=config_data,
        benchmarks=benchmarks,
        replace=True
    )
    
    if verbose:
        print(f"   ✓ Replaced {original_count} LLM-generated benchmarks")
        print(f"   ✓ Added {len(benchmarks)} directly extracted benchmarks")
    
    # =========================================================================
    # STEP 4: Validate configuration quality (optional)
    # =========================================================================
    validation_results = {}

    if validate_sql or validate_instructions:
        if verbose:
            print("\n🔍 Running validation checks...")

        config = config_data["genie_space_config"]

        # SQL Validation
        if validate_sql:
            if verbose:
                print("   Running SQL validation...")

            # Get tables for validation context
            from src.models import GenieSpaceTable
            tables = [
                GenieSpaceTable(**table) for table in config.get("tables", [])
            ]

            sql_validator = SQLValidator(available_tables=tables)
            sql_results = sql_validator.validate_config_sql(config)
            validation_results["sql_validation"] = sql_results

            if verbose:
                summary = sql_results["summary"]
                print(f"   SQL Validation Results:")
                print(f"     - Total queries: {summary['total_queries']}")
                print(f"     - Valid queries: {summary['valid_queries']}")
                print(f"     - With errors: {summary['queries_with_errors']}")
                print(f"     - With warnings: {summary['queries_with_warnings']}")

                # Show first few errors if any
                all_reports = sql_results["example_queries"] + sql_results["sql_expressions"]
                errors_shown = 0
                for report in all_reports:
                    if not report.is_valid and errors_shown < 3:
                        print(f"\n   ⚠️  SQL Error in query:")
                        for error in report.get_errors()[:2]:
                            print(f"       - {error.message}")
                        errors_shown += 1

        # Instruction Quality Validation
        if validate_instructions:
            if verbose:
                print("\n   Running instruction quality scoring...")

            scorer = InstructionQualityScorer()
            quality_report = scorer.score_config_instructions(config)
            validation_results["instruction_quality"] = {
                "average_score": quality_report.average_score,
                "total_instructions": quality_report.total_instructions,
                "high_quality_count": quality_report.high_quality_count,
                "medium_quality_count": quality_report.medium_quality_count,
                "low_quality_count": quality_report.low_quality_count,
                "scores": [
                    {
                        "score": s.total_score,
                        "grade": s.grade(),
                        "specificity": s.specificity_score,
                        "structure": s.structure_score,
                        "clarity": s.clarity_score,
                        "issues": s.issues,
                        "suggestions": s.suggestions
                    }
                    for s in quality_report.instruction_scores
                ]
            }

            if verbose:
                print(f"   Instruction Quality Results:")
                print(f"     - Average score: {quality_report.average_score:.1f}/100")
                print(f"     - High quality (≥80): {quality_report.high_quality_count}")
                print(f"     - Medium quality (60-79): {quality_report.medium_quality_count}")
                print(f"     - Low quality (<60): {quality_report.low_quality_count}")

                # Show issues for low-quality instructions
                for i, score in enumerate(quality_report.instruction_scores):
                    if score.total_score < 60:
                        print(f"\n   ⚠️  Low-quality instruction #{i+1} (Score: {score.total_score:.1f}):")
                        for issue in score.issues[:2]:
                            print(f"       - {issue}")

        # Save validation report if requested
        if validation_output:
            if verbose:
                print(f"\n   Saving validation report to {validation_output}...")

            validation_path = Path(validation_output)
            validation_path.parent.mkdir(parents=True, exist_ok=True)

            with open(validation_path, 'w', encoding='utf-8') as f:
                # Convert reports to JSON-serializable format
                serializable_results = {
                    "sql_validation": {},
                    "instruction_quality": validation_results.get("instruction_quality", {})
                }

                if "sql_validation" in validation_results:
                    sql_val = validation_results["sql_validation"]
                    serializable_results["sql_validation"] = {
                        "summary": sql_val["summary"],
                        "example_queries": [
                            {
                                "is_valid": r.is_valid,
                                "tables": list(r.tables_referenced),
                                "columns": list(r.columns_referenced),
                                "has_joins": r.has_explicit_joins,
                                "errors": [{"severity": e.severity, "category": e.category, "message": e.message} for e in r.get_errors()],
                                "warnings": [{"severity": w.severity, "category": w.category, "message": w.message} for w in r.get_warnings()],
                            }
                            for r in sql_val["example_queries"]
                        ]
                    }

                json.dump(serializable_results, f, indent=2, ensure_ascii=False)

            if verbose:
                print(f"   ✓ Validation report saved")

    # =========================================================================
    # STEP 5: Save final configuration
    # =========================================================================
    if verbose:
        print(f"\n💾 Saving configuration to {output_path}...")

    with open(output_path_obj, 'w', encoding='utf-8') as f:
        json.dump(config_data, f, indent=2, ensure_ascii=False)

    if verbose:
        print(f"   ✓ Configuration saved")

    # Add validation results to return value
    if validation_results:
        config_data["_validation_results"] = validation_results

    return config_data
