"""Configuration generation module."""

import json
import os
from pathlib import Path
from typing import Optional, Dict, Any

from src.prompt.prompt_builder import PromptBuilder
from src.llm.databricks_llm import DatabricksFoundationModelClient, DatabricksLLMClient
from src.utils.benchmark_extractor import (
    extract_all_benchmarks,
    merge_benchmarks_into_config,
    validate_benchmarks
)


def generate_config(
    requirements_path: str,
    output_path: str = "output/genie_space_config.json",
    model: str = "databricks-gpt-5-2",
    endpoint: Optional[str] = None,
    context_doc: str = "src/prompt/templates/curate_effective_genie.md",
    output_doc: str = "src/prompt/templates/genie_api.md",
    max_tokens: int = 16000,
    temperature: float = 0.1,
    no_reasoning: bool = False,
    faq_section: str = "## 📊 질문 목록 (FAQ)",
    databricks_host: Optional[str] = None,
    databricks_token: Optional[str] = None,
    verbose: bool = True
) -> Dict[str, Any]:
    """
    Generate Genie space configuration with direct benchmark extraction.
    
    This function:
    1. Generates the configuration using LLM (for tables, instructions, examples, etc.)
    2. Extracts benchmarks DIRECTLY from requirements document (bypassing LLM)
    3. Merges the extracted benchmarks into the configuration
    4. Saves the final configuration
    
    Args:
        requirements_path: Path to requirements document
        output_path: Output file path for generated config
        model: Foundation model to use (e.g., databricks-gpt-5-2)
        endpoint: Custom serving endpoint name (alternative to foundation model)
        context_doc: Path to context document (best practices)
        output_doc: Path to output format document (API docs)
        max_tokens: Maximum tokens to generate
        temperature: Sampling temperature (0.0-1.0)
        no_reasoning: Skip reasoning in LLM output
        faq_section: FAQ section title to extract benchmarks from
        databricks_host: Databricks workspace URL
        databricks_token: Databricks personal access token
        verbose: Print progress messages
        
    Returns:
        dict: Generated configuration
        
    Raises:
        ValueError: If credentials are missing
        Exception: If generation or extraction fails
    """
    # Get credentials
    host = databricks_host or os.getenv("DATABRICKS_HOST")
    token = databricks_token or os.getenv("DATABRICKS_TOKEN")
    
    if not host or not token:
        raise ValueError(
            "DATABRICKS_HOST and DATABRICKS_TOKEN must be set. "
            "Either set environment variables or pass as arguments."
        )
    
    # Ensure output directory exists
    output_path_obj = Path(output_path)
    output_path_obj.parent.mkdir(parents=True, exist_ok=True)
    
    # =========================================================================
    # STEP 1: Generate configuration with LLM
    # =========================================================================
    if verbose:
        print("📝 Generating configuration with LLM...")
    
    # Build prompt
    builder = PromptBuilder(
        context_doc_path=context_doc,
        output_doc_path=output_doc,
        input_data_path=requirements_path
    )
    
    if no_reasoning:
        prompt = builder.build_prompt()
    else:
        prompt = builder.build_prompt_with_reasoning()
    
    if verbose:
        print(f"   Prompt: {len(prompt)} characters")
    
    # Initialize LLM client
    if endpoint:
        if verbose:
            print(f"   Using custom endpoint: {endpoint}")
        llm_client = DatabricksLLMClient(
            endpoint_name=endpoint,
            databricks_host=host,
            databricks_token=token
        )
    else:
        if verbose:
            print(f"   Using foundation model: {model}")
        llm_client = DatabricksFoundationModelClient(
            model_name=model,
            databricks_host=host,
            databricks_token=token
        )
    
    # Generate configuration
    if verbose:
        print(f"   Calling LLM (max_tokens={max_tokens}, temperature={temperature})...")
        print("   This may take 30-60 seconds...")
    
    response = llm_client.generate_genie_config(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature
    )
    
    if verbose:
        print("   ✓ Configuration generated by LLM")
    
    # Extract config
    config_data = response.model_dump()
    
    # Show summary
    if verbose:
        config = config_data["genie_space_config"]
        print(f"\n   Space Name: {config['space_name']}")
        print(f"   Tables: {len(config['tables'])}")
        print(f"   Instructions: {len(config['instructions'])}")
        print(f"   Example SQL Queries: {len(config['example_sql_queries'])}")
        print(f"   LLM-Generated Benchmarks: {len(config.get('benchmark_questions', []))}")
    
    # =========================================================================
    # STEP 2: Extract benchmarks directly from requirements
    # =========================================================================
    if verbose:
        print("\n📊 Extracting benchmarks from requirements...")
    
    benchmarks = extract_all_benchmarks(
        requirements_path=requirements_path,
        include_faq=True,
        include_sample_queries=True,
        faq_section_title=faq_section
    )
    
    # Count by type
    faq_count = sum(1 for bm in benchmarks if bm.get('source') == 'faq')
    sample_query_count = sum(1 for bm in benchmarks if bm.get('source') == 'sample_query')
    
    if verbose:
        print(f"   ✓ Extracted {len(benchmarks)} benchmarks")
        print(f"     - FAQ questions: {faq_count}")
        print(f"     - Sample queries: {sample_query_count}")
    
    # Validate benchmarks
    report = validate_benchmarks(benchmarks)
    if verbose:
        print(f"   Validation: {report['valid_count']}/{report['total_count']} valid")
        if report['issues']:
            print(f"   ⚠ {len(report['issues'])} validation issues")
    
    # =========================================================================
    # STEP 3: Merge benchmarks into configuration
    # =========================================================================
    if verbose:
        print("\n🔗 Merging benchmarks into configuration...")
    
    original_count = len(config_data["genie_space_config"].get("benchmark_questions", []))
    
    config_data = merge_benchmarks_into_config(
        config=config_data,
        benchmarks=benchmarks,
        replace=True
    )
    
    if verbose:
        print(f"   ✓ Replaced {original_count} LLM-generated benchmarks")
        print(f"   ✓ Added {len(benchmarks)} directly extracted benchmarks")
    
    # =========================================================================
    # STEP 4: Save final configuration
    # =========================================================================
    if verbose:
        print(f"\n💾 Saving configuration to {output_path}...")
    
    with open(output_path_obj, 'w', encoding='utf-8') as f:
        json.dump(config_data, f, indent=2, ensure_ascii=False)
    
    if verbose:
        print(f"   ✓ Configuration saved")
    
    return config_data
